name: Phalcon Framework
description: "Phosphorum - Official Phalcon Forum. Get support using Phalcon, the next-generation PHP Framework."
keywords: "php, phalcon, phalcon php, php framework, faster php framework, forum, phosphorum"
google_analytics': "UA-133802124-6"
asset_tag: "20200614175000"
